<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>  
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<title><?php echo $this->title; ?></title>
	<?php echo $this->headLink()->setStylesheet('/styles/style.css', 'screen, projection'); ?>
	<?php echo $this->headScript()->appendFile('/scripts/jquery-1.3.2.min.js', 'text/javascript'); ?>
</head>
<body>

    <div id="page">
    
	    <div id="header">
	    </div><!-- header -->
	    
	    <div id="main">
	        <?php echo $this->render('inc/messages.phtml'); ?>
	        <?php echo $this->layout()->content ?>
		</div><!-- main -->
        
        <div id="ajax_loader" style="display: none";>
            <?php echo $this->image('img/ajax-loader.gif', array('alt' => '')); ?>
        </div>
		
		<div id="footer">
	    </div><!-- footer -->
	    
    </div>
    
</body>
</html>