<?php
/**
 * Dictionary
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 5845 2009-06-09 07:36:57Z jwage $
 */
class Dictionary extends BaseDictionary
{
    /**
     * Returns array with amount of all rows in database and rows for chosen page
     *
     * @param integer $col
     * @param integer $sort
     * @param integer $offset
     * @param integer $resultPerPage
     * @return array
     */
    public function getList($col = 1, $sort = 1, $offset = 0, $resultPerPage = 15){
        
        $order = ($col == 1) ? 'd_key' : 'd_value';
        $order.= ($sort == 1) ? ' ASC' : ' DESC';
        
        $result['rows'] = 
        Doctrine_Query::create()->select('d.d_key, d.d_value')
                                ->addFrom('Dictionary d')
                                ->orderBy($order)
                                ->offset($offset)
                                ->limit($resultPerPage)
                                ->fetchArray();
        
        $result['count'] = 
        Doctrine_Query::create()->select('COUNT(d.d_key) AS count')
                                ->addFrom('Dictionary d')
                                ->fetchArray();
        $result['count'] = $result['count'][0]['count'];
                                
        return $result;
    }
    
    /**
     * Returns array with amount rows satisfy the conditionan and that rows for chosen page
     *
     * @param string $text
     * @param integer $col
     * @param integer $sort
     * @param integer $offset
     * @param integer $resultPerPage
     * @return array
     */
    public function getSearching($text = '', $col = 1, $sort = 1, $offset = 0, $resultPerPage = 15){
        
        $order = ($col == 1) ? 'd_key' : 'd_value';
        $order.= ($sort == 1) ? ' ASC' : ' DESC';
        
        $result['rows'] = 
        Doctrine_Query::create()->select('d.d_key, d.d_value')
                                ->addFrom('Dictionary d')
                                ->where('d.d_key LIKE "%'.$text.'%"')
                                ->orderBy($order)
                                ->offset($offset)
                                ->limit($resultPerPage)
                                ->fetchArray();
        
        $result['count'] = 
        Doctrine_Query::create()->select('COUNT(d.d_key) AS count')
                                ->addFrom('Dictionary d')
                                ->where('d.d_key LIKE "%'.$text.'%"')
                                ->fetchArray();
        $result['count'] = $result['count'][0]['count'];
                                
        return $result;
    }
}