<?php if ($this->notEmptyMessages !== NULL) { ?>
<div class="content2">
	<?php if (!empty($this->messages)){ ?>
		<p class="success">
		<img alt="" src="/img/icons/tick.png"/>
		<?php foreach ($this->messages as $message) { ?> 
		    <?php echo $message; ?><br />
		<?php } ?>
		</p>
	<?php } ?>
	
	<?php if (!empty($this->warnings)){ ?>
		<p class="notice">
		<img alt="" src="/img/icons/information.png"/>
		<?php foreach ($this->warnings as $warning) { ?> 
		    <?php echo $warning; ?><br />
		<?php } ?>
		</p>
	<?php } ?>
	
	<?php if (!empty($this->errors)){ ?>
		<p class="error">
		<img alt="" src="/img/icons/cross.png" />
		<?php foreach ($this->errors as $error) { ?> 
		    <?php echo $error; ?><br />
		<?php } ?>
		</p>
	<?php } ?>
</div>
<?php } ?>